
version: '3.7'
services:
  kafka-producer-wikimedia:
    image: ${GROUP_ID}/wikimedia.producer.service:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/kafka-producer-wikimedia/logs"
    user: root
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8080 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m
    networks:
      - ${GLOBAL_NETWORK:-services}