
version: '3.7'
services:
  kafka-producer-wikimedia:
    image: ${GROUP_ID}/wikimedia.producer.service:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/kafka-producer-wikimedia/logs"
    user: root
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8080 -Dspring.profiles.active=dev-docker -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}
  kafka-consumer-wikimedia:
    image: ${GROUP_ID}/wikimedia.consumer.service:${SERVICE_VERSION:-latest}
    ports:
      - "8888:8888"
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/kafka-consumer-wikimedia/logs"
    environment:
      #      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8888 -Dspring.profiles.active=dev-docker -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}